# Generated by Django 2.0.1 on 2018-02-01 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0001_initial'),
        ('account', '0001_initial'),
        ('rate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='r_l',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.Lecture'),
        ),
        migrations.AddField(
            model_name='rating',
            name='r_s',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Student'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('r_id', 'r_l', 'r_s')},
        ),
    ]
