# Generated by Django 2.0.1 on 2018-02-01 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('l_id', models.AutoField(primary_key=True, serialize=False)),
                ('l_name', models.CharField(max_length=20, verbose_name='강의명')),
                ('semester', models.CharField(help_text='e.g. 2018 봄/가을', max_length=10, verbose_name='학기')),
                ('l_credit', models.IntegerField(verbose_name='학점')),
            ],
            options={
                'verbose_name': '강의',
                'verbose_name_plural': '강의',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_l_name', models.CharField(max_length=10, verbose_name='성')),
                ('p_f_name', models.CharField(max_length=10, verbose_name='이름')),
                ('p_gender', models.CharField(choices=[('M', '남'), ('F', '여')], max_length=1, verbose_name='성별')),
                ('p_office_loc', models.IntegerField(verbose_name='건물번호')),
                ('p_office_num', models.CharField(help_text='031-XXX-XXXX', max_length=15, verbose_name='오피스번호')),
                ('p_email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('have_kname', models.CharField(choices=[('T', 'Yes'), ('F', 'No')], help_text='This is used exclusively for naming.', max_length=1, verbose_name='Is it Korean name ?')),
                ('p_d', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Department', verbose_name='소속대학')),
            ],
            options={
                'verbose_name': '교수',
                'verbose_name_plural': '교수',
            },
        ),
        migrations.AddField(
            model_name='lecture',
            name='l_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.Professor', verbose_name='담당교수'),
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together={('l_name', 'l_p')},
        ),
    ]
